theme: jekyll-theme-minimal
title: oMEGACat Survey
description: The oMEGACat survey is a Hubble Space Telescope and VLT/MUSE survey of the central regions of omega Centauri, the Milky Way's most massive cluster.
